/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.DbUtils;
import entites.Etudiant;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import service.EtudiantServiceImpl;
import service.InterfaceEtudiantService;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class AjouterEtudiantPanel extends javax.swing.JPanel {

    private final InterfaceEtudiantService etudiantService = new EtudiantServiceImpl();

    /**
     * Creates new form EtudiantPanel
     */
    public AjouterEtudiantPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        EnregistrerButton = new javax.swing.JButton();
        AnnulerButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        IDTextField = new javax.swing.JTextField();
        PRENOMTextField = new javax.swing.JTextField();
        NOMTextField = new javax.swing.JTextField();
        DATE_NAISSANCETextField = new javax.swing.JTextField();
        FILIAREComboBox = new javax.swing.JComboBox<>();
        NIVEAUComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jTextField1.setText("jTextField1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setBackground(new java.awt.Color(0, 153, 153));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Etudiant", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(255, 0, 102))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ajouter Etudiant");

        EnregistrerButton.setText("Enregistrer");
        EnregistrerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnregistrerButtonActionPerformed(evt);
            }
        });

        AnnulerButton.setText("Annuler");
        AnnulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("ID :");

        jLabel4.setText("PRENOM :");

        jLabel5.setText("NOM :");

        jLabel6.setText("DATE_NAISSANCE :");

        jLabel7.setText("FILIARE :");

        jLabel8.setText("NIVEAU :");

        IDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextFieldActionPerformed(evt);
            }
        });

        DATE_NAISSANCETextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DATE_NAISSANCETextFieldActionPerformed(evt);
            }
        });

        FILIAREComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INFORMATIQUE", "GENIE CIVIL", "MECANIQUE", "GESTION"}));
        FILIAREComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FILIAREComboBoxActionPerformed(evt);
            }
        });

        NIVEAUComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Licence 1", "Licence 2", "Licence 3", "Master 1", "Master 2" }));

        jLabel10.setText("2021-01-18");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AnnulerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EnregistrerButton)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IDTextField)
                    .addComponent(PRENOMTextField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NIVEAUComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 142, Short.MAX_VALUE)
                            .addComponent(FILIAREComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DATE_NAISSANCETextField)
                            .addComponent(NOMTextField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PRENOMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(NOMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(DATE_NAISSANCETextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(FILIAREComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(NIVEAUComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnregistrerButton)
                    .addComponent(AnnulerButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DATE_NAISSANCETextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DATE_NAISSANCETextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DATE_NAISSANCETextFieldActionPerformed

    private void FILIAREComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FILIAREComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FILIAREComboBoxActionPerformed

    private void IDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTextFieldActionPerformed

    private void AnnulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerButtonActionPerformed

        IDTextField.setText("");
        PRENOMTextField.setText("");
        NOMTextField.setText("");
        DATE_NAISSANCETextField.setText("");

    }//GEN-LAST:event_AnnulerButtonActionPerformed

    private void EnregistrerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnregistrerButtonActionPerformed

        try {

            String id = IDTextField.getText();
            if (id == null || id.isBlank()) {
                JOptionPane.showMessageDialog(this, "L'ID est obligatoire", "ID invalide", JOptionPane.ERROR_MESSAGE);
            }

            String prenom = PRENOMTextField.getText();
            if (prenom == null || prenom.isBlank()) {
                JOptionPane.showMessageDialog(this, "Le prenom est obligatoire", "prenom invalide", JOptionPane.ERROR_MESSAGE);
            }

            String nom = NOMTextField.getText();
            if (nom == null || nom.isBlank()) {
                JOptionPane.showMessageDialog(this, "Le nom est obligatoire", "nom invalide", JOptionPane.ERROR_MESSAGE);
            }

            String dateNaissance = DATE_NAISSANCETextField.getText();
            Date date = DbUtils.SQL_FORMAT.parse(dateNaissance);
            String filiaire = FILIAREComboBox.getItemAt(WIDTH);
            String niveau = NIVEAUComboBox.getItemAt(WIDTH);

            Etudiant e = new Etudiant();
            e.setId(id);
            e.setPrenom(prenom);
            e.setNom(nom);
            e.setDateNaissance(date);
            e.getnomFiliaire();
            e.getNiveau();

            etudiantService.ajouterEtudiant(e);
        } catch (ParseException ex) {
            Logger.getLogger(AjouterEtudiantPanel.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }

        MainApp app = MainApp.getInstance();
        app.setContentPane(new ListerEtudiantFiliairePanel());
        app.revalidate();
        app.repaint();

    }//GEN-LAST:event_EnregistrerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnnulerButton;
    private javax.swing.JTextField DATE_NAISSANCETextField;
    private javax.swing.JButton EnregistrerButton;
    private javax.swing.JComboBox<String> FILIAREComboBox;
    private javax.swing.JTextField IDTextField;
    private javax.swing.JComboBox<String> NIVEAUComboBox;
    private javax.swing.JTextField NOMTextField;
    private javax.swing.JTextField PRENOMTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
