/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import entites.Filiaire;
import javax.swing.JOptionPane;
import service.FiliaireServiceImpl;
import service.InterfaceFiliaireService;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class AjouterFiliairePanel extends javax.swing.JPanel {

    private final FiliaireServiceImpl filiaireService = new FiliaireServiceImpl();

    /**
     * Creates new form FiliairePanel
     */
    public AjouterFiliairePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        EnregistrerButton = new javax.swing.JButton();
        AnnulerButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        NOM_FILIAIRETextField = new javax.swing.JTextField();

        jLabel3.setText("jLabel3");

        jLabel6.setText("jLabel6");

        setBackground(new java.awt.Color(0, 153, 153));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filiaire", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(255, 0, 102))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ajouter Filiaire");

        EnregistrerButton.setText("Enregistrer");
        EnregistrerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnregistrerButtonActionPerformed(evt);
            }
        });

        AnnulerButton.setText("Annuler");
        AnnulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("NOM_FILIARE :");

        NOM_FILIAIRETextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOM_FILIAIRETextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AnnulerButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NOM_FILIAIRETextField, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EnregistrerButton)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NOM_FILIAIRETextField)
                    .addComponent(jLabel2))
                .addGap(168, 168, 168)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnregistrerButton)
                    .addComponent(AnnulerButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EnregistrerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnregistrerButtonActionPerformed

        String nomFiliaire = NOM_FILIAIRETextField.getText();
        if (nomFiliaire == null || nomFiliaire.isBlank()) {
            JOptionPane.showMessageDialog(this, "Le nomFiliaire est obligatoire", "nomFiliaire invalide", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Filiaire filiaire = new Filiaire(nomFiliaire);
        filiaireService.ajouterFiliare(filiaire);

        JOptionPane.showMessageDialog(this, "filiaire ajouter avec succes", "ajout Validee", JOptionPane.INFORMATION_MESSAGE);
        NOM_FILIAIRETextField.setText("");
        MainApp app = MainApp.getInstance();
        app.setContentPane(new SupprimerFiliairePanel());
        app.revalidate();
        app.repaint();

    }//GEN-LAST:event_EnregistrerButtonActionPerformed

    private void NOM_FILIAIRETextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOM_FILIAIRETextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NOM_FILIAIRETextFieldActionPerformed

    private void AnnulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerButtonActionPerformed
        NOM_FILIAIRETextField.setText("");
    }//GEN-LAST:event_AnnulerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnnulerButton;
    private javax.swing.JButton EnregistrerButton;
    private javax.swing.JTextField NOM_FILIAIRETextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
