/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JScrollPane;
import service.EtudiantServiceImpl;
import service.InterfaceEtudiantService;
import service.InterfaceFiliaireService;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class MainApp extends javax.swing.JFrame {

    private static MainApp instance;

    /**
     * Creates new form MainApp
     */
    public MainApp() {
        initComponents();
    }

    public static MainApp getInstance() {
        if (instance == null) {
            instance = new MainApp();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        ETUDIANTMenu = new javax.swing.JMenu();
        AjouterEtudiantCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        ListerEtudiantFiliaireCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        ListerEtudiantClasseCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        ListerALLEtudiantCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        FORMATIONMenu = new javax.swing.JMenu();
        AjouterFiliaireCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        ModifierFiliaireCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        SupprimerFiliaireCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setForeground(new java.awt.Color(0, 153, 153));

        jMenuBar1.setForeground(new java.awt.Color(255, 0, 102));

        ETUDIANTMenu.setText("ETUDIANT");
        ETUDIANTMenu.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N

        AjouterEtudiantCheckBoxMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        AjouterEtudiantCheckBoxMenuItem.setSelected(true);
        AjouterEtudiantCheckBoxMenuItem.setText("Ajouter un Etudiant");
        AjouterEtudiantCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterEtudiantCheckBoxMenuItemActionPerformed(evt);
            }
        });
        ETUDIANTMenu.add(AjouterEtudiantCheckBoxMenuItem);

        ListerEtudiantFiliaireCheckBoxMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ListerEtudiantFiliaireCheckBoxMenuItem.setSelected(true);
        ListerEtudiantFiliaireCheckBoxMenuItem.setText("Lister Etudiant Filiaire");
        ListerEtudiantFiliaireCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListerEtudiantFiliaireCheckBoxMenuItemActionPerformed(evt);
            }
        });
        ETUDIANTMenu.add(ListerEtudiantFiliaireCheckBoxMenuItem);

        ListerEtudiantClasseCheckBoxMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ListerEtudiantClasseCheckBoxMenuItem.setSelected(true);
        ListerEtudiantClasseCheckBoxMenuItem.setText("Lister Etudiant Classe");
        ListerEtudiantClasseCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListerEtudiantClasseCheckBoxMenuItemActionPerformed(evt);
            }
        });
        ETUDIANTMenu.add(ListerEtudiantClasseCheckBoxMenuItem);

        ListerALLEtudiantCheckBoxMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ListerALLEtudiantCheckBoxMenuItem.setSelected(true);
        ListerALLEtudiantCheckBoxMenuItem.setText("Lister Tous Les Etudiants");
        ListerALLEtudiantCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListerALLEtudiantCheckBoxMenuItemActionPerformed(evt);
            }
        });
        ETUDIANTMenu.add(ListerALLEtudiantCheckBoxMenuItem);

        jMenuBar1.add(ETUDIANTMenu);

        FORMATIONMenu.setText("FORMATION");
        FORMATIONMenu.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N

        AjouterFiliaireCheckBoxMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        AjouterFiliaireCheckBoxMenuItem.setSelected(true);
        AjouterFiliaireCheckBoxMenuItem.setText("Ajouter une Filiaire");
        AjouterFiliaireCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterFiliaireCheckBoxMenuItemActionPerformed(evt);
            }
        });
        FORMATIONMenu.add(AjouterFiliaireCheckBoxMenuItem);

        ModifierFiliaireCheckBoxMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ModifierFiliaireCheckBoxMenuItem.setSelected(true);
        ModifierFiliaireCheckBoxMenuItem.setText("Modifier une Filiare");
        ModifierFiliaireCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierFiliaireCheckBoxMenuItemActionPerformed(evt);
            }
        });
        FORMATIONMenu.add(ModifierFiliaireCheckBoxMenuItem);

        SupprimerFiliaireCheckBoxMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        SupprimerFiliaireCheckBoxMenuItem.setSelected(true);
        SupprimerFiliaireCheckBoxMenuItem.setText("Supprimer Filiaire");
        SupprimerFiliaireCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerFiliaireCheckBoxMenuItemActionPerformed(evt);
            }
        });
        FORMATIONMenu.add(SupprimerFiliaireCheckBoxMenuItem);

        jMenuBar1.add(FORMATIONMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AjouterEtudiantCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterEtudiantCheckBoxMenuItemActionPerformed
        AjouterEtudiantPanel contenu = new AjouterEtudiantPanel();
        JScrollPane scrollpan = new JScrollPane(contenu);
        setContentPane(scrollpan);
        revalidate();
        repaint();
    }//GEN-LAST:event_AjouterEtudiantCheckBoxMenuItemActionPerformed

    private void AjouterFiliaireCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterFiliaireCheckBoxMenuItemActionPerformed
        AjouterFiliairePanel contenu = new AjouterFiliairePanel();
        JScrollPane scrollpan = new JScrollPane(contenu);
        setContentPane(scrollpan);
        revalidate();
        repaint();
    }//GEN-LAST:event_AjouterFiliaireCheckBoxMenuItemActionPerformed

    private void ModifierFiliaireCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierFiliaireCheckBoxMenuItemActionPerformed
        ModifierFiliairePanel contenu = new ModifierFiliairePanel();
        JScrollPane scrollpan = new JScrollPane(contenu);
        setContentPane(scrollpan);
        revalidate();
        repaint();
    }//GEN-LAST:event_ModifierFiliaireCheckBoxMenuItemActionPerformed

    private void SupprimerFiliaireCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerFiliaireCheckBoxMenuItemActionPerformed
        SupprimerFiliairePanel contenu = new SupprimerFiliairePanel();
        JScrollPane scrollpan = new JScrollPane(contenu);
        setContentPane(scrollpan);
        revalidate();
        repaint();
    }//GEN-LAST:event_SupprimerFiliaireCheckBoxMenuItemActionPerformed

    private void ListerEtudiantFiliaireCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListerEtudiantFiliaireCheckBoxMenuItemActionPerformed
        ListerEtudiantFiliairePanel contenu = new ListerEtudiantFiliairePanel();
        JScrollPane scrollpan = new JScrollPane(contenu);
        setContentPane(scrollpan);
        revalidate();
        repaint();
    }//GEN-LAST:event_ListerEtudiantFiliaireCheckBoxMenuItemActionPerformed

    private void ListerEtudiantClasseCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListerEtudiantClasseCheckBoxMenuItemActionPerformed
        ListerEtudiantClassePanel contenu = new ListerEtudiantClassePanel();
        JScrollPane scrollpan = new JScrollPane(contenu);
        setContentPane(scrollpan);
        revalidate();
        repaint();
    }//GEN-LAST:event_ListerEtudiantClasseCheckBoxMenuItemActionPerformed

    private void ListerALLEtudiantCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListerALLEtudiantCheckBoxMenuItemActionPerformed
        ListerAllEtudiantPanel contenu = new ListerAllEtudiantPanel();
        JScrollPane scrollpan = new JScrollPane(contenu);
        setContentPane(scrollpan);
        revalidate();
        repaint();
    }//GEN-LAST:event_ListerALLEtudiantCheckBoxMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainApp.getInstance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem AjouterEtudiantCheckBoxMenuItem;
    private javax.swing.JCheckBoxMenuItem AjouterFiliaireCheckBoxMenuItem;
    private javax.swing.JMenu ETUDIANTMenu;
    private javax.swing.JMenu FORMATIONMenu;
    private javax.swing.JCheckBoxMenuItem ListerALLEtudiantCheckBoxMenuItem;
    private javax.swing.JCheckBoxMenuItem ListerEtudiantClasseCheckBoxMenuItem;
    private javax.swing.JCheckBoxMenuItem ListerEtudiantFiliaireCheckBoxMenuItem;
    private javax.swing.JCheckBoxMenuItem ModifierFiliaireCheckBoxMenuItem;
    private javax.swing.JCheckBoxMenuItem SupprimerFiliaireCheckBoxMenuItem;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
